version: "3.8"

services:
  db:
    image: postgres:17.4
   # container_name: movieDB
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: moviesoftware
    ports:
      - "5432:5432"
    volumes:
      - kinosoftware_postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: movies_backend
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/moviesoftware
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8000:8080"

  frontend:
    build: ./frontend
    container_name: movies_frontend
    depends_on:
      - backend
    environment:
      VITE_API_URL: http://localhost:8000
    ports:
      - "3000:80"

volumes:
  kinosoftware_postgres_data:
    external: true
